[functions.send-contact-email]
enabled = true
verify_jwt = false   # 👈 set to false if the contact form is public
import_map = "./functions/send-contact-email/deno.json"
entrypoint = "./functions/send-contact-email/index.ts"

